### ISSUE TITLE
problems with webpack-dev-server's HMR

### ISSUE THREAD

**Issue by pstoica** [MoOx/eslint-loader#10]
I'm using this with HMR right now and noticed a couple of things.

In my console, I see things like:
```
[90m18:4[39m  [31merror[39m  'x' is not defined  [90mno-undef[39m
```

In the root of my project some files keep getting made like `\033[22m\033[39m`.

I'm guessing these are the terminal colors being sent through and WDS is goofing up? I can try to look into it more later. This is great otherwise, thanks!

**Comment by MoOx** [comment]
Indeed it's colors send by the eslint stylish reporter.
Does your terminal support colors ?

**Comment by pstoica** [comment]
Yep, my terminal supports colors and it shows up fine there.

But for some reason webpack-dev-server is also receiving the reporter warnings and spitting it out into the console and accidentally making files. I wonder if changing emitWarning to console.warn would prevent this? To be honest, I'm not sure where the bug is. This might be something in webpack-dev-server.

**Comment by MoOx** [comment]
I am using dev-server & don't have this issue on iTerm 2 OS X Yosemite.

**Comment by pstoica** [comment]
Cool, sounds like it's something on my end. I'll close for now. Thanks!

**Comment by MoOx** [comment]
Reopening since I am now getting these weirdness in my browser console. We need to improve that if possible.

**Comment by nkbt** [comment]
```javascript
Server.prototype._sendStats = function(socket, stats, force) {
	if(!force && stats && stats.assets && stats.assets.every(function(asset) {
		return !asset.emitted;
	})) return;
	socket.emit("hash", stats.hash);
	if(stats.errors.length > 0)
		socket.emit("errors", stats.errors);
	else if(stats.warnings.length > 0)
		socket.emit("warnings", stats.warnings);
	else
		socket.emit("ok");
}
```

Webpack dev server simply sends warnings/errors over websocket "as is".

This means if we emit pre-formatted messages in the loader, we will get:

```
5:::{
  "name": "warnings",
  "args": [
    [
      "./src/app/Landing.js\n\n\u001b[4m/src/app/Test.js\u001b[24m\n  \u001b[90m67:11\u001b[39m  \u001b[33mwarning\u001b[39m  Block must not be padded by blank lines  \u001b[90mpadded-blocks\u001b[39m\n\n\u001b[33m\u001b[1m✖ 1 problem (0 errors, 1 warning)\n\u001b[22m\u001b[39m"
    ]
  ]
}
```
So maybe it is better not to format ESLint messages and keep them plain by default here: https://github.com/MoOx/eslint-loader/blob/master/index.js#L77-L79?

**Comment by nkbt** [comment]
Actually,

```javascript
    {
      formatter: require("eslint/lib/formatters/compact"),
    },
```

does the trick pretty well. Messages are still properly coloured. Just look a little bit less fancy.

**Comment by MoOx** [comment]
Maybe we should make a PR to webpack dev server to remove terminal color ?

**Comment by nkbt** [comment]
That could be a solution. At least get some discussion around it.

**Comment by nkbt** [comment]
Just checked webpack-dev-server. This problem is already fixed in commit: https://github.com/webpack/webpack-dev-server/commit/6ea80ce82ef5020e112f9f7c69c37134329e19ca

And it is available in [v1.8.0](https://github.com/webpack/webpack-dev-server/releases/tag/v1.8.0).

![fixed](http://dl.dropbox.com/u/932526/Screenshot/2015-04/20150412-214709.png)

**Comment by MoOx** [comment]
Nice. Good to know. Thanks!

**Comment by nkbt** [comment]
I found that ansi escaping was not removed from warnings. Only from errors. So made a PR
https://github.com/webpack/webpack-dev-server/pull/154

**Comment by MoOx** [comment]
Oh, cool ! Thanks for this :)
