### ISSUE TITLE
Accept options as query parameters as well

### ISSUE THREAD

**Issue by mohsen1** [MoOx/eslint-loader#100]
We are using two different pre-loaders for ES5 and ES6 and have two seperate `eslintrc` files for each. We want to pass each `eslintrc` to each of our preLoaders.

I'm hoping to set `configFile` for each preLoader via query like this:

```js
    {
        test: /\.js$/,
        loader: 'eslint',
        query: {configFile: './.eslintrc.js'},
        exclude: [
            /node_modules/,
            /\.m\.js$/
        ]
    },
    {
        test: /\.m\.js/,
        query: {
            configFile: './eslintrc.m.js'
        },
        loader: 'eslint',
        exclude: [
            /node_modules/,
            /[a-z]\.js$/
        ]
    }
```

**Comment by mohsen1** [comment]
Its actually possible to pass options in query string. It's just not documented. 

Per [these lines](https://github.com/MoOx/eslint-loader/blob/master/index.js#L100-L109) you are accepting options from query string as well.

**Comment by MoOx** [comment]
It's definitely documented in the first section here https://github.com/MoOx/eslint-loader#options
