### ISSUE TITLE
Does not work with eslint-import-resolver-webpack

### ISSUE THREAD

**Issue by calvinnwq** [MoOx/eslint-loader#103]
``` javascript
// webpack.config.js
module.exports = {
  ...
  resolve: {
    root: [
      path.resolve(__dirname, './src')
    ],
    modulesDirectories: ['node_modules']
  }
  ...
}
```

``` javascript
// .eslintrc.js
module.exports = {
  ...
  'plugins': [ 'import' ],
  'settings': {
    'import/resolver': 'webpack'
  }
}
```

It seems that the config `settings` that is used by eslint-import-resolver-webpack is not a config in the eslint [CLIEngine](http://eslint.org/docs/developer-guide/nodejs-api#cliengine).

If i ran eslint from the terminal it works, but doesn't work if it's going through eslint-loader

**Comment by MoOx** [comment]
> It seems that the config settings that is used by eslint-import-resolver-webpack is not a config in the eslint CLIEngine.

Any other idea on what to use then?

**Comment by IanVS** [comment]
>It seems that the config settings that is used by eslint-import-resolver-webpack is not a config in the eslint CLIEngine.

This is true, but the keys of the config file are not being passed directly as keys to CLIEngine.  I think you're having a different problem.  I found that I needed to turn off the `cache` option when setting things up, or else it seemed that changes to the `.eslintrc` had no effect, which might have been what you were seeing.

**Comment by Zephir77167** [comment]
I have the same problem, and the cache is off. Any ideas?

**Comment by MoOx** [comment]
Seems to work then.
