### ISSUE TITLE
ESLint-loader fails on errors in webpack 2

### ISSUE THREAD

**Issue by eranimo** [MoOx/eslint-loader#104]
Using `webpack@2.1.0-beta.20`

My config looks like this:

```js
{
    cwd: '/path/to/somewhere'
    cache: true,
    failOnWarning: false,
    failOnError: false
}
```

Webpack build returns with linting errors (specifically, some from react). It successfully builds, but it returns status code 1.

**Comment by MoOx** [comment]
eslint-loader works for me with webpack 2 (I am using it for months).
Can you send your errors?

**Comment by eranimo** [comment]
Never mind, my bad! Adding `emitWarning: true` worked
