### ISSUE TITLE
build doesn't finish when used with eslint-config-airbnb-base

### ISSUE THREAD

**Issue by Eschon** [MoOx/eslint-loader#107]
I use `eslint-loader` as a preloader in my build process. My eslint config extends `eslint-config-airbnb` when I run my build it doesn't finish I let it run for over 24h just to make sure.

I found out that it works just fine when I disable the `eslint-loader` preloader. If the preloader is enabled it also works if I only use my own rules without the `eslint-config-airbnb`. I also tried `eslint-config-airbnb-base` to narrow down the problem and it doesn't work.

To make sure that my own rules are not a problem I tried it with `eslint-config-airbnb` and `eslint-config-airbnb-base` on their own and got the same problem.

Here are some additional informations for the versions that I run:
node: 6.3.1
eslint-loader: 1.5.0
eslint-config-airbnb: 10.0.0
webpack: 1.13.1

Please tell me if you need some other informations.

**Comment by MoOx** [comment]
Did you try to use it as a loader, not a preLoader? Can you try another shareable config?

**Comment by Eschon** [comment]
I just tested it as a loader and it has the same problems.

I'll try to make a minimal configuration that reproduces the problem when I find the time

**Comment by Eschon** [comment]
I tried to set up a small project that has the same problem but I wasn't able to.

It seems that it isn't a problem with the `eslint-config-airbnb` alone.

Since it isn't really necessary for me to run eslint when building I'll close this for now. Maybe I'll have another look when I have more time.

**Comment by MoOx** [comment]
This is weird indeed. Maybe some of the linted code is responsible?
I know that https://github.com/facebookincubator/create-react-app use this eslint-loader and is not having issue with airbnb config if I am correct.

**Comment by Eschon** [comment]
Yes I used `create-react-app` to create my project but I ejected immediately.
After a while of developing the problem started to appear. I tried to undo some changes but the bug still was there.

The only way I could get rid of it was disabling `eslint-loader` or the `eslint-config-airbnb`

**Comment by MoOx** [comment]
Maybe a specific rule is having an issue with a specific piece of code... :(
