### ISSUE TITLE
not displaying errors in browser console

### ISSUE THREAD

**Issue by stevenmusumeche** [MoOx/eslint-loader#108]
I believe I have something misconfigured, but I cannot solve it.  I'm trying to get ESLint errors to show up in my browser console during development, but they are not showing up.  The linting results are displayed in my console, just not in the browser.  Here is my config:

    module: {
        preLoaders: [
            {
                test: /\.jsx?$/,
                loader: "eslint-loader",
            }
        ],
        loaders: [
            {
                test: /(\.js|\.jsx)$/,
                exclude: /node_modules/,
                loaders: ['babel']
            },
            {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: "url-loader?limit=10000&mimetype=application/font-woff&name=[name].[ext]"
            },
            {
                test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: "file-loader?name=[name].[ext]"
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i, loaders: ['file']
            }
        ]
    },

**Comment by stevenmusumeche** [comment]
Stupid mistake, I had `NoErrorsPlugin` and removed it to fix this issue.

**Comment by latviancoder** [comment]
Well, i have the same problem and removing NoErrorsPlugin didn't help :/ Here is my config:

```
module: {
	preLoaders: [
		{test: /\.js$/, loader: 'eslint', exclude: /node_modules/}
	],
	loaders: [
		{
			test: /.json$/,
			loaders: [
				'json'
			]
		},
		{
			test: /\.(css|less)$/,
			loaders: [
				'style',
				'css?sourceMap',
				'less?sourceMap',
				'postcss'
			]
		},
		{
			test: /\.js$/,
			exclude: /node_modules/,
			loaders: [
				'ng-annotate',
				'babel'
			]
		},
		{
			test: /.html$/,
			loaders: [
				'html'
			]
		},
		{
			test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
			loader: 'url?limit=10000',
		},
		{
			test: /\.(png|gif|jpg)$/,
			loader: "url-loader?limit=10000"
		},
		{
			test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
			loader: 'file',
		}
	]
},
plugins: [
	new webpack.DefinePlugin({'process.env.ENV': JSON.stringify('dev')}),
	new webpack.ProvidePlugin({ 'moment': 'moment', 'humanizeDuration': 'humanize-duration' }),
	new webpack.optimize.OccurrenceOrderPlugin(),
	new HtmlWebpackPlugin({
		template: conf.path.src('index.html'),
		inject: true
	})
],
postcss: () => [autoprefixer],
debug: true,
devtool: 'inline-source-map',
output: {
	path: path.join(process.cwd(), conf.paths.tmp),
	filename: 'index.js'
},
eslint: {
	configFile: '.eslintrc',
	emitError: true,
	emitWarning: true,
},
entry: [`./${conf.path.src('index')}`]
```

**Comment by MoOx** [comment]
This is a webpack configuration issue, not an eslint-loader issue. Try StackOverflow ;)
