### ISSUE TITLE
Conflict with NoErrorsPlugin

### ISSUE THREAD

**Issue by mnpenner** [MoOx/eslint-loader#111]
I know it's mentioned as a [gotcha](https://github.com/MoOx/eslint-loader#noerrorsplugin), but is there anything that can be done about that?

I was relying on `NoErrorsPlugin` to prevent us from deploying a broken build into production.

I've enabled `eslint.failOnError`, but I believe that's a subset of what `NoErrorsPlugin` would have caught.

**Comment by MoOx** [comment]
I think the main problem of NoErrorsPlugin + eslint-loader is when you use both in development. I don't see any problem of using both for a production build, but I may miss something as I just woke up :)

**Comment by mnpenner** [comment]
> NoErrorsPlugin prevents Webpack from outputting anything into a bundle. So even ESLint warnings will fail the build. No matter what error settings are used for eslint-loader.

If I understand that right, this means that a single ESLint warning will cause the build to fail?

But we don't always manage to fix all the warnings before a production build -- that's why they're set to warnings, not errors.

What if I set `quiet: true` for production -- would warnings still cause the build to fail?

**Comment by MoOx** [comment]
I guess yeah, the quiet option is good for you in that case.

**Comment by mnpenner** [comment]
I can live with that. I'd prefer if errors always failed the build and warnings never did, but as long as the errors don't go to production, this'll be good enough. Thanks!

**Comment by MoOx** [comment]
NoErrorsPlugin is likely to produce the same issue for any loader/plugin that will trigger warnings. Maybe you should ask for an option in this plugin so it only REALLY block for errors, not warnings.
