### ISSUE TITLE
Disable logs into dev console

### ISSUE THREAD

**Issue by ilyakatz** [MoOx/eslint-loader#112]
I am not sure if this is the right place, but Is there a way to disable lint errors into browser dev console?

**Comment by MoOx** [comment]
No, we don't control this. You have to see that directly with webpack or webpack-dev-server.

**Comment by JikkuJose** [comment]
@ilyakatz did you find a solution for this?

**Comment by ilyakatz** [comment]
Not really, but I added an environmental variable that controls whether or not eslint is added to webpack configuration. Not the same, but until I find a better way

```javascript
if (isDev && !process.env.DISABLE_LINT) {
  config.module.preLoaders.push(
    {
      test: /\.jsx?$/,
      loaders: ['eslint'],
      exclude: /(node_modules|bower_components)/,
    }
  );
}
```
