### ISSUE TITLE
webpack@^2.1.0-beta.23 throws "Configuration has an unknown property 'eslint'"

### ISSUE THREAD

**Issue by alexsunxl** [MoOx/eslint-loader#113]
[ webpack  v2.1.0-beta.23](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23)   is not support setting 'eslint' in the exports.

`
module.exports = {
  eslint: {
    configFile: 'path/.eslintrc'
  }
}
`

[error print](http://7xj9do.com1.z0.glb.clouddn.com/ln/2016-09-20%2011-35-45%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

how can i set the eslint config file path.

**Comment by MoOx** [comment]
Your picture is not accessible, I get a "not found".

**Comment by alexsunxl** [comment]
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'eslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }

**Comment by MoOx** [comment]
Well that's a breaking change... Semver is not really respected...
So latest webpack version validate all options. Ouch. @TheLarkInn @sokra are you aware  that some loaders use this pattern to pass options? I know more than one that use this...
Maybe you could expose an API so we can add some entries...? Or maybe know query accept more than json?

@alexsunxl any idea where would you like to get your options?

**Comment by alexsunxl** [comment]
I think add path to rules's query may be awesome. 

webpack.config.js
`
module.exports = {
...
  module: {
    rules: [
        {
            enforce: 'left',
            test: /\.js$/,
            loader: 'eslint-loader',
            query: {
               configFile: './.eslintrc.js'
            },
            },
       ...
    ]
  }
...
}
`

And I try to change code in my locale, can I PR after finish?

**Comment by MoOx** [comment]
query should already be supported.

**Comment by alexsunxl** [comment]
I see 
```
  var config = assign(
    // loader defaults
    {
      formatter: require("eslint/lib/formatters/stylish"),
    },
    // user defaults
    this.options.eslint || {},
    // loader query string
    loaderUtils.parseQuery(this.query)
  )
```
but it is not working.  I don't know why
eslint not read my eslintrc

**Comment by MoOx** [comment]
Maybe try with ``configFile: __DIRNAME + '/.eslintrc.js'``?

**Comment by alexsunxl** [comment]
Finally I find the mistake is that the 'enforce' shoule be 'right' to instead of preLoaders.
Thank you so much ~~

```
module.exports = { 
  ...
  module: { 
    rules: [ 
        {
            enforce: 'right',
            loader: 'eslint-loader',
            query: {
               configFile: 'path'
            },
        },
       ...
    ]
  }
  ...
}
```

**Comment by MoOx** [comment]
The current official solution with webpack@2.1 beta23 seems to be

Change this

```js
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'foo.chunk.js',
    path: './dist'
  },
  eslint: {
    /* your eslint loader config */
  }
}
```

to this

```js
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'foo.chunk.js',
    path: './dist'
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        eslint: {
          /* your eslint loader config */
        }
      }
    })
  ]
}
```

**Comment by alexsunxl** [comment]
I see , :+1:

**Comment by MoOx** [comment]
Reopening until I push a notice in the README

**Comment by eriknyk** [comment]
not sure what is the complete solution,
still using preLoaders or not?, use new webpack.LoaderOptionsPlugin(), instead eslint section, 
still it is not working for me, using webpack 2.1.0-beta.25

Regards.

**Comment by alexsunxl** [comment]
@eriknyk 
'preLoaders' is no longer use.

``` javascript
module.exports = { 
  ...
  module: { 
    // loaders or rules is all the same
    loaders: [ 
        {
            enforce: 'right',
            loader: 'eslint-loader',
            // query is same with the [new webpack.LoaderOptionsPlugin()]
            query: {
               configFile: 'path'
            },
        },
       ...
    ]
  }
  ...
}
```

**Comment by eriknyk** [comment]
thank you @alexsunxl I will try it.

**Comment by alexsunxl** [comment]
@eriknyk  in webpack@2.1.0-beta.25  [enforce: 'right'] should be [enforce: 'pre']
see the [webpack  v2.1.0-beta.24](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.24)

**Comment by eriknyk** [comment]
it worked, thank you a lot @alexsunxl

**Comment by johnthecat** [comment]
Hi, can't migrate to beta 25, because webpack throws error
`configuration has an unknown property 'failOnError'`
It also doesn't work after `webpack.LoaderOptionsPlugin` used.
Can you help me?

**Comment by kristianmandrup** [comment]
Please update Readme with a section for Webpack 2.1 beta25+ configuration :)
I'm using this setup which works:

```js
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'eslint'
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          babelrc: true,
          cacheDirectory: true
        }
      }
    ]
  }
```

**Comment by ClementParis016** [comment]
I can't see what's the proper use of `webpack.LoaderOptionsPlugin` should be, since this works:
```js
{
    test: /\.js$/,
    include: [path.join(__dirname, 'src/app')],
    loader: 'eslint-loader',
    enforce: 'pre',
    query: {
       configFile: path.join(__dirname, '.eslintrc')
     },
},
``` 

but this doesn't (falls back to default eslint config):
```js
 plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        eslint: {
          configFile: path.join(__dirname, '.eslintrc')
        }
      }
    })
]
```

**Comment by hinok** [comment]
@ClementParis016 I think that you've missed `test: {...}` so it should be

```javascript
 plugins: [
    new webpack.LoaderOptionsPlugin({
      test: /\.js$/,
      options: {
        eslint: {
          configFile: path.join(__dirname, '.eslintrc')
        }
      }
    })
]
```

Works for me on webpack `2.1.0-beta.27`

**Comment by barraponto** [comment]
This is from a working configuration:

```javascript

/* eslint-env node */
const path = require('path');
module.exports = {
  // entry, output, other top-level options ...
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        enforce: 'pre',
        use: [{loader: 'eslint-loader'}],
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {presets: [['es2015', {modules: false}]]},
          },
        ],
      },
    ],
  },
  // no need for plugins
};
```

Note that the official Webpack 2 documentation no longer supports `loaders` or `query`, and using `enfore: pre` requires a separate rule (although you could just leave `eslint-loader` as the last rule, since they are applied in reverse order).
