### ISSUE TITLE
eslint-loader does not appear to work on Windows

### ISSUE THREAD

**Issue by Ian5015** [MoOx/eslint-loader#120]
We have a mix of developers using Mac or Windows PC, on the Mac side the eslint-loader works exactly as expected but in Windows we aren't getting any output. The loader seems to load correctly including the configs in both scenarios. The only difference that I can tell is operating system. If I pass "failOnError: true" it will fail correctly on the Mac side for any errors and does not fail on the Windows side, so it appears as if the eslint-loader isn't starting at all or is perhaps failing silently.

**Comment by MoOx** [comment]
Hi. Thanks for reporting this issue. But to be honest I don't see why this would not work, as we are not doing anything special with paths or files. We are mainly here consuming eslint cli api.
Will see if I have time to setup appveyor to add CI for windows.

**Comment by Ian5015** [comment]
I was definitely hesitant to open this issue to begin with because from what I can tell the package should work fine. It is the only preloader we're currently using, so I wonder if there's an issue with the version of webpack that we're using with preloaders on Windows. I'm going to attempt to spend a small amount of time today testing with different versions of webpack (we are still using <2.0).

I appreciate your response to the issue and the contribution team's work on this loader.

**Comment by MoOx** [comment]
You can try to use it as a loader (I never used this loader as a preLoader)).

**Comment by Ian5015** [comment]
Still no dice.

**Comment by julmot** [comment]
For me it doesn't work either:

![2017-07-13 16_41_42-cmd](https://user-images.githubusercontent.com/8310677/28171919-435381ac-67ea-11e7-8429-e633706a46cd.png)

**Comment by MoOx** [comment]
What version of node/npm/eslint are you using?

**Comment by julmot** [comment]
@MoOx See https://github.com/MoOx/eslint-loader/pull/185

**Comment by MoOx** [comment]
Closing since instructions have been added to readme.
