### ISSUE TITLE
outputReport option writes report last file checked only

### ISSUE THREAD

**Issue by smokku** [MoOx/eslint-loader#121]
I am using an example configuration for `checkstyle.xml`. The issue is that the file generated contains style report just for the last file that was checked, not the aggregate of all the files checked by the `eslint-loader`. It kind of beats the purpose of storing the raport.

**Comment by ArielZhang** [comment]
I got the same issue, how can I get around this issue before the fix merged ? @smokku

**Comment by ArielZhang** [comment]
@MoOx any chance we can merge this fix ? thanks very much.

**Comment by smokku** [comment]
@ArielZhang just put in your `package.json`:
```json
"eslint-loader": "git+https://github.com/smokku/eslint-loader#e0e3dea",
```

**Comment by ArielZhang** [comment]
@smokku thanks! but after switch to your fix, I got the same result, only one file existed in the final report xml.

**Comment by smokku** [comment]
@ArielZhang you also need to set `eslint.outputReport.filePath` to `'checkstyle-[hash].xml'` in `webpack.conf.js`

**Comment by MoOx** [comment]
> any chance we can merge this fix ? thanks very much.

I won't merge a "fix" without the corresponding test. If you want this to get this merged, you can help writing a test for it :)

**Comment by ArielZhang** [comment]
@smokku thanks, I got all report xml now !

**Comment by supamanda** [comment]
To anyone using the fix suggested above, this is no longer available:

```
"eslint-loader": "git+https://github.com/smokku/eslint-loader#e0e3dea"
```

**Comment by smokku** [comment]
@supamanda This change was merged - just use latest `eslint-loader` :)

**Comment by supamanda** [comment]
I'm using 1.6.1 and I'm still getting the same problem. @smokku I noticed one of your changes was in a PR that hasn't been merged to master (https://github.com/MoOx/eslint-loader/pull/134) - is that what you are talking about?

**Comment by deryni** [comment]
Sorry, I lost track of this for a bit. I just got #134 back in shape (re-filed as #160 because of git shenanigans) and the tests are passing this time so hopefully that means the PR can get merged in soon.

**Comment by jerm-s** [comment]
Hi, 

When generating report with eslint-loader only a single problem is generated. Below are the results 

![eslint-loader](https://cloud.githubusercontent.com/assets/17397188/26141180/227147a8-3b0d-11e7-9615-cccf0bca223f.png)

^ Result generated by eslint-loader

![eslint](https://cloud.githubusercontent.com/assets/17397188/26141181/227a68ba-3b0d-11e7-9ff0-ae81b1191675.png)

^ Result generated by running `eslint app/** -f html -o ./app/test/eslint-report.html` on commmand line


and my webpack config:

````
var path = require("path");

module.exports = {
	entry: './app/index.js',
	output: {
		path: path.resolve(__dirname, "dist"),
		filename: 'bundle.js'
	},
	module: {
		rules: [
			{
				enforce: "pre",
		        test: /\.js$/,
		        exclude: /node_modules/,
		        loader: "eslint-loader",
		        options: {
		        	// Fail only on errors
          			failOnWarning: false,
          			failOnError: false,

          			// Toggle autofix
          			fix: true,

          			emitWarning: true,

		        	outputReport: {
		        		filePath: 'eslint_report.html',
		        		formatter: require('eslint/lib/formatters/html')
		        	}
	        	}
	                }
		]
	}
}
````

Why isit not generating all the result? 

Thank you! 

eslint version: 3.19.0
eslint-loader version: 1.7.1

**Comment by snavaneeth78** [comment]
+1

**Comment by AjayU** [comment]
Anybody got this working? I am also facing the same issue.

**Comment by MoOx** [comment]
I guess nobody explicitly started this. So please provide a failing test via a PR. Then if you have time, you can work on a fix :)

**Comment by IlchenkoAnton** [comment]
The problem with the output of only the last file with an error is not corrected. I use:
"eslint": "^ 4.11.0", "
"eslint-loader": "^ 1.9.0"

webpack.config.js
`options: {
    outputReport: {
        filePath: 'eslint-report.html',
        formatter: require('eslint/lib/formatters/html')
    }
 }`

I want to note that the report is not the last file with an error, but the first one.

**Comment by nvrsprasad** [comment]
I am also facing the same issue. Is there any solution for it?

**Comment by Stephs15** [comment]
I'm also facing this issue. All errors are being shown on the console but on the report just the first one

"eslint": "^4.19.1",
"eslint-loader": "^2.0.0",

webpack config
`outputReport: {
            filePath: 'eslint-results.html',
            formatter: require('eslint/lib/formatters/html')
        }`
Any solutions so far?

**Comment by IlchenkoAnton** [comment]
Unfortunately, the decision did not find

чт, 28 июн. 2018 г. в 13:36, Stephs15 <notifications@github.com>:

**Comment by sethomas** [comment]
+1
