### ISSUE TITLE
Cache persists when eslint rules have changed

### ISSUE THREAD

**Issue by wrakky** [MoOx/eslint-loader#124]
The eslint-loader cache is only ever invalidated when a file is changed. This means that if you make changes to your eslint rules, the last cached lint result will still be output by eslint-loader and not the outcome based on the updated rules. The only way to fix this is to either modify each file being linted or manually delete the cache.

The entire cache should be invalidated if the eslint rules have changed.

**Comment by MoOx** [comment]
Indeed. What to make a PR for this?

**Comment by wrakky** [comment]
I started work on a fix last night. I'll submit a PR later today for initial review so you can check my solution isn't completely crazy.

**Comment by wrakky** [comment]
Resolved by #151
