### ISSUE TITLE
Restructure Testing

### ISSUE THREAD

**Issue by wrakky** [MoOx/eslint-loader#140]
The current tests have some shortcomings that need addressing due to changes in the codebase and new versions of webpack.

Tests should do the following which they currently do not:
* Run each individual test in isolation to prevent state from being shared between them
* Run on multiple versions of webpack now that webpack2 is pretty much ready for use

Suggested changes:
* Replace tape as the test runner with [Ava](https://github.com/avajs/ava) which runs all tests in separate node processes due to tape [not supporting this](https://github.com/substack/tape/issues/309)
* Update test and travis config to support multiple versions of webpack similar to how babel-loader [does it](https://github.com/babel/babel-loader/blob/master/.travis.yml).

**Comment by MoOx** [comment]
Closed by #141
