### ISSUE TITLE
Eslint with webpack dev server. How to lint only just updated files?

### ISSUE THREAD

**Issue by boochamoocha** [MoOx/eslint-loader#145]
I using eslint-loader with webpack dev server. After every file update eslint check all files of project and show result in console.  I want to lint only updated file. How can achieve it?

**Comment by MoOx** [comment]
It should be the default behavior. Maybe webpack keep the warnings in memory or something?

**Comment by boochamoocha** [comment]
Can somebody show webpack config for dev server? 
I using webpack 1.14, and setup from readme.md with preloaders section. Every time i updated 1 file i receive mess eslint errors in console about all files in project.

**Comment by MoOx** [comment]
Errors & warnings are probably cached by webpack anyway, as every file change the entire bundle is recompiled. Maybe I said something wrong by saying it's the default behavior.
Anyway, you should probably fix all errors as this loader is mainly to prevent errors during development with a clean codebase.

Maybe try to check eslint --fix :)

**Comment by MoOx** [comment]
Closing as it seems a generic webpack "issue".
