### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by acontreras89** [MoOx/eslint-loader#146]
Line 75 of the [README](https://github.com/MoOx/eslint-loader/blame/master/README.md#L75) file should be split in two.

```
};```
```
should be
```
};\n```
```
instead

**Comment by MoOx** [comment]
Thanks!

Would take less time to edit the file directly :)

<img width="1077" alt="screen shot 2017-01-19 at 07 50 34" src="https://cloud.githubusercontent.com/assets/157534/22096462/fb96683c-de1b-11e6-8784-dee7679f2692.png">

**Comment by acontreras89** [comment]
You're very welcome @MoOx !

Since I have no write privileges, I'd need to create a fork and issue a pull request. I didn't deem necessary to fork the repo for just this :sweat_smile: 

I'll definitely consider doing so if I find more interesting ways to contribute, tho :)

**Comment by MoOx** [comment]
FYI, GitHub makes this for you and will even offers a "delete" repo from the web interface when PR is merged ;)
