### ISSUE TITLE
How to specify `max-warnings`?

### ISSUE THREAD

**Issue by pconerly** [MoOx/eslint-loader#147]
How do I specify the command-line argument `max-warnings` with eslint-loader?

I've tried adding this to my webpack config:
```
module.exports = {
  ...
  eslint: {
    maxWarnings: 1,
  },
  ...
}
```

I also tried changing my eslint loader config to:
```
  module: {
    // First, run the linter.
    // It's important to do this before Babel processes the JS.
    preLoaders: [
      {
        test: /\.(js|jsx)$/,
        loader: 'eslint?max-warnings=0',
        include: paths.src,
        exclude: [paths.foo, paths.bar],
      },
    ],
```

**Comment by MoOx** [comment]
Is this an eslint option?

**Comment by pconerly** [comment]
It's a command-line flag: http://eslint.org/docs/user-guide/command-line-interface 

and it may be coded as an option internally? Here's the PR that added it: https://github.com/eslint/eslint/pull/3580/files

**Comment by pconerly** [comment]
I'm digging more into this-- this issue may reveal some light: https://github.com/eslint/eslint/issues/4125

Your `eslint-loader` uses CLIEngine, and since CLIEngine doesn't handle exiting, they did not include max-warnings into the cliengine. :-/

**Comment by pconerly** [comment]
So yeah, thinking about this, the eslint recommendation is to code this option up in any plugins that use CLIEngine. Would you accept a PR that added a maxWarnings option to `eslint-loader`?

**Comment by MoOx** [comment]
Sure!

**Comment by pconerly** [comment]
I was mucking around in the code and I found `failOnWarning` which is exactly what I wanted. Closing :D
