### ISSUE TITLE
Cache option enabled, but no cache folder exists.

### ISSUE THREAD

**Issue by alberth8** [MoOx/eslint-loader#149]
According to the eslint-loader docs, if I have `cache: true`, the results should be stored in `./node_modules/.cache`. However, I do not see anything, only `./node_modules/.bin`.

I added the `cache` option to my webpack config:

```
eslint: {
  configFile: 'src/.eslintrc',
  cache: true,
},
```

And when I build, it doesn't create a `.cache` folder. Am I missing something?

**Comment by viankakrisna** [comment]
maybe findCacheDir thunks returned false? you can try to console.log the `cachePath` on https://github.com/MoOx/eslint-loader/blob/master/index.js#L168 and see where it points to. If it's false, cache wont be created.

**Comment by MoOx** [comment]
@alberth8 what version of webpack are you using? Can you provide full config?

**Comment by MoOx** [comment]
Closing due to the lack of feedback.
