### ISSUE TITLE
arrow function not supported for me 

### ISSUE THREAD

**Issue by zzzgit** [MoOx/eslint-loader#150]
```javascript
use: [{
    loader: 'eslint-loader', 
    options: {
        rules: {semi: 0},
        ecmaFeatures:{
            arrowFunctions:true
        }
    }
}],
```

![image](https://cloud.githubusercontent.com/assets/1060733/22551013/d9280bca-e98d-11e6-802f-09549fc426d4.png)

**Comment by MoOx** [comment]
This is a bad configuration. `ecmaFeatures` needs to be in a specific section.
See http://eslint.org/docs/user-guide/configuring#specifying-parser-options
