### ISSUE TITLE
0.6.0 - Default reporter doesn't emit output

### ISSUE THREAD

**Issue by ericclemmons** [MoOx/eslint-loader#16]
In my `webpack.config.js`:

```javascript
  eslint: {
    configFile: '.eslintrc',
    emitError: true,
    emitWarning: true
  },
```

No output is rendered when i purposefully introduce an error.

_However_, I can see there are indeed errors to report by going against the README:

```javascript
  eslint: {
    configFile: '.eslintrc',
    emitError: true,
    emitWarning: true,
    reporter: function(results) {
      console.log(stylish.call(this, results));
      return stylish.call(this, results);
    }
  },
```

```
webpack: bundle is now INVALID.

<text>
  14:0  error  'return' outside of function

✖ 1 problem (1 error, 0 warnings)
```

Peculiar, eh?

**Comment by MoOx** [comment]
- You can't use emitError and emitWarning at the same time.

> By default the loader will auto adjust error reporting depending on eslint errors/warnings counts. You can still force this behavior

- You don't need to specify .eslintrc file (it's the default value of eslint).
- [Tests show that the output works](https://travis-ci.org/MoOx/eslint-loader).
- A reporter SHOULD NOT use console.log(), webpack takes care of the display.

So it's probably related to your webpack config.

**Comment by ericclemmons** [comment]
Shoot :( 

@MoOx Do you think it matters I'm using the webpack-dev-server?

**Comment by ericclemmons** [comment]
Also, TBH, I turned everything "on" explicitly to try & debug why this wasn't working.

**Comment by MoOx** [comment]
I am using webpack dev server too and it's working perfectly.
emitError & emitWarning are part of webpack api so it is probably related to that.
Do you get error when you do not use dev-server ? (just `webpack` command to make a build).

**Comment by MoOx** [comment]
@ericclemmons do you find where the problem came from ?

**Comment by ericclemmons** [comment]
@MoOx Thanks for checking in!  Nope, I didn't, but I verified that your tests pass so...  ¯\_(ツ)_/¯
