### ISSUE TITLE
Webpack + ES6 + ESLINT

### ISSUE THREAD

**Issue by Tilican** [MoOx/eslint-loader#162]
Hello,
i have a little problem with your ESLINT.
dependencies: [here](https://puu.sh/uzMJp/3ffcf5dfc6.txt)
eslintrc : [here](https://puu.sh/uzMM2/140a3661b7.txt)

webpack rules : 
```
rules: [
          {
            enforce: "pre",
            test: /\.js$/,
            include: this.srcPathAbsolute,
            options: {
              configFile: path.resolve('./.eslintrc'),
            },
            loader: "eslint-loader",
          },
          {
            test: /\.js$/,
            include: this.srcPathAbsolute,
            loader: "babel-loader",
          },
        ],
```
in my react file i use :` import '../styles/app.css';`
eslint say : Module parse failed, You may need an appropriate loader to handle this file type.

i have this since u upgrade webpack.

thx

**Comment by NTARelix** [comment]
None of your rules specify how to handle .css files. Here are some suggested loaders, depending on what you're trying to do with the css file:

- [style-loader](https://github.com/webpack/style-loader)
- [postcss-loader](https://github.com/postcss/postcss-loader)
- [file-loader](https://github.com/webpack-contrib/file-loader)

Here's a page from the webpack v1 docs that describes some scenarios: [https://webpack.github.io/docs/stylesheets.html](https://webpack.github.io/docs/stylesheets.html)

**Comment by MoOx** [comment]
`Module parse failed, You may need an appropriate loader to handle this file type.`

This is not an eslint error. It's webpack default error when you have a file type not handled by any loader.
