### ISSUE TITLE
Cache option blocks configFile option

### ISSUE THREAD

**Issue by Snowshield** [MoOx/eslint-loader#171]
Cache option is upper then configFile. Webpack rule **doesnt use** config file (tested with global eslint variable):
```
      {
        test: /\.(js|vue)$/,
        loader: "eslint-loader",
        include: /src/,
        enforce: "pre",
        options: {
          formatter: require("eslint-friendly-formatter"),
          cache: DEVELOPMENT,
          configFile:  path.resolve(__dirname, '.eslintrc.js'),
        }
      },
```
If cache option is lower then configFile is loaded but eslint **doesnt read rules** in `.eslintrc.js`
```
      {
        test: /\.(js|vue)$/,
        loader: "eslint-loader",
        include: /src/,
        enforce: "pre",
        options: {
          formatter: require("eslint-friendly-formatter"),
          configFile:  path.resolve(__dirname, '.eslintrc.js'),
          cache: DEVELOPMENT,
        }
      },
```

**Comment by MoOx** [comment]
This does not make any sense. Objects are not ordered in JavaScript anyway.

**Comment by MoOx** [comment]
Closing to due to lack of feedback.

**Comment by hxlhxl** [comment]
This is truely happened.

**Comment by MoOx** [comment]
Please reopen an issue if necessary, with all the details you can as nobody that actually use this loader is maintaining it. I do the bare minimum but not even use it for months...

**Comment by galvarez421** [comment]
I can confirm that this is still an issue, although I'm not sure if the order of the cache property has anything to do with it. If I define configFile and cache is set to true, the configFile is not used. If I comment out cache: true, then the configFile is used.

**Comment by galvarez421** [comment]
This is possibly related to caching issues described in #190, #214, and #222.
