### ISSUE TITLE
Errors in dev mode rendered in console instead of red box

### ISSUE THREAD

**Issue by steida** [MoOx/eslint-loader#174]
Maybe I am overlooking something, but errors showing red overlay breaks DX.
I would love to have an option to render errors as warnings for dev mode.

**Comment by MoOx** [comment]
This is a webpack configuration problem. Eslint just reports errors/warnings with webpack api. You might want to use `emitWarning: true` to avoid eslint errors to be reported as webpack errors (but warnings instead).

**Comment by steida** [comment]
Wow it works. Super nice. Thank you 🍫
