### ISSUE TITLE
How to lint files without producing an output bundle?

### ISSUE THREAD

**Issue by nickmccurdy** [MoOx/eslint-loader#184]
This is more of a usage question about using webpack with eslint-loader than an issue with eslint-loader itself, since I'm not sure if this is possible to implement solely from a webpack loader.

Depending on the tooling used, it may make sense to lint files that never need to be included in even a development bundle (for example, configuration files and test files). I am unsure of the best approach to linting files that shouldn't have output bundles generated by webpack (besides using eslint directly just for those files, which would be outside the webpack development workflow). My current workaround is to have an extra webpack bundle which has all my test files as entry points and sets `output.path` to `os.tmpdir()`, but this feels really hacky and the bundle takes a while to build (probably because of webpack traversing through dependencies which don't need to be linted anyway).

**Comment by MoOx** [comment]
This module is a loader that can only do his job on file consumed via webpack require/import. So I think you should probably just use another tool.
