### ISSUE TITLE
eslint-loader prevents webpack from running after upgrading to webpack 3.1+

### ISSUE THREAD

**Issue by JadedDragoon** [MoOx/eslint-loader#189]
I get the following error after upgrading to Webpack 3.3.0.  I downgraded to Webpack 3.1.0 without resolving the issue. Unfortunately, I cannot downgrade further without also downgrading a number of other modules which have fixes I need. This is preventing me from using Webpack with eslint-loader enabled.

```
    ERROR in ./js/main.jssrc
    Module build failed: TypeError: loaderUtils.getOptions is not a function
        at Object.module.exports (/home/ubuntu/workspace/node_modules/eslint-loader/index.js:150:17)
     @ multi ./js/main.jssrc
```

After further investigation, it seems eslint-loader had suddenly started using a very outdated version of loader-utils after I upgraded from Webpack 3.0 to Webpack 3.3:
```
├─┬ eslint-loader@1.9.0
│ └── loader-utils@0.2.17 
```

I solved by manually installing `npm i loader-utils@1`. Not sure how this happened as eslint-loader specifically requests loader-utils@^1.0.2 and I haven't touched eslint-loader in any way.

Regardless, apparently, this *isn't* an eslint-loader issue but some sort of weird npm issue. I'm leaving this here so you can at least see it and come to your own conclusions before closing.

**Comment by MoOx** [comment]
Like you said, it's not directly an eslint-loader issue as we have 1.x as a dep https://github.com/MoOx/eslint-loader/blob/667baf33828405b47ba42930ccac0ccaa6546c0b/package.json#L23

I guess you got some weird upgrade or something. I am closing this as user using search will find you experience. Thanks for sharing!
