### ISSUE TITLE
Option to display output to console only, not devtools

### ISSUE THREAD

**Issue by avrelaun** [MoOx/eslint-loader#191]
When I'm importing code or while debugging, the output of eslint is redundant between my shell and the devtools console.

Or I'd like to see only logs from the currently running app on my devtools, not being polluted by eslint output. I know that this annoyance shall be resolved by solving the eslint errors, but when I'm coding I do not want to see the console or debugger warnings, yet I'd like to see those in my shell. Plus, some warnings are just warnings and definitely shouldn't make it harder to see the actual console messages from the app.

I'd like to be able to configure the desired output (devtools console, shell console, or both).

I understand that this may not be an eslint-loader issue, but open it to keep track of it and for future references. Related webpack issue: [https://github.com/webpack/webpack/issues/5441](https://github.com/webpack/webpack/issues/5441)

**Comment by MoOx** [comment]
Original issue have been closed. Don't have time to dig.
Closing to due to lack of feedback.

Feel free to reopen with more details if necessary.
