### ISSUE TITLE
Displays wrong file line numbers

### ISSUE THREAD

**Issue by nbosco** [MoOx/eslint-loader#197]
* **Webpack**
3.5.5
* **ESLint Version:** 
v4.3.0
* **Node Version:**
v6.10.3

Eslint-loader displays the wrong line numbers for file run via webpack

Eg Image. https://gyazo.com/1c395f6226b7abfcc071b3849e611012

**Comment by MoOx** [comment]
You are probably running eslint on transformed files.
eslint-loader needs to be used as your first loader (so the last in your list) or as a pre-loader. See readme.
Unless you share your webpack config we cannot help you.
