### ISSUE TITLE
Custom reporter support?

### ISSUE THREAD

**Issue by Dashed** [MoOx/eslint-loader#2]
Possible to have custom reporter support like https://github.com/webpack/jshint-loader does?

**Comment by Dashed** [comment]
Hmmm. I'm unsure if this is CLI only: https://github.com/eslint/eslint/issues/1260

**Comment by MoOx** [comment]
Open to PR for this :)

**Comment by Dashed** [comment]
I haven't looked into this yet. AFAIK, ESlint doesn't seem to have a config for it.

**Comment by MoOx** [comment]
We should use webpack api for this (emitErrors/emitWarnings)
