### ISSUE TITLE
Validation Warning for webpack config

### ISSUE THREAD

**Issue by eyalcohen4** [MoOx/eslint-loader#200]
Hey! 
Great loader, thanks for that.

eslint-loader version: 1.9.0
webpack versions: 3.6.0

I have a problem with my config - 
After I'm running `webpack-dev-server --hot --inline --config webpack/webpack.dev.js`, 
I get validation warnings about my webpack.config files - 

    ● Validation Warning:

      Unknown option "target" with value "web" was found.
      This is probably a typing mistake. Fixing it will remove this message.

    ● Validation Warning:

      Unknown option "entry" with value "./index.js" was found.
      This is probably a typing mistake. Fixing it will remove this message.

and so on, for each webpack config property.

my loader settings look like this -

     {
        enforce: 'pre',
        test: /\.(js|jsx)/,
        loader: 'eslint-loader',
        exclude: [/node_modules/, /webpack/],
        options: {
          configFile: path.resolve(__dirname, '../.eslintrc.json'),
       }

How can I tell the loader not to check for the webpack config files?
Thanks!

**Comment by MoOx** [comment]
This loader doesn't do any kind of validation, so it's either a webpack config problem or an eslint config problem.

**Comment by eyalcohen4** [comment]
thanks for your response!
