### ISSUE TITLE
Recommend to use `preLoaders` section instead of `loaders`

### ISSUE THREAD

**Issue by nkbt** [MoOx/eslint-loader#27]
Using `eslint-loader` with `babel-loader` and strict ES6 validation rules fails with lots of errors, since it tries to check code which is transpiled by babel.

To avoid any confusion in loaders ordering, suggest to use `preLoaders` section instead.

**Comment by MoOx** [comment]
Closed by 252bbe8088615146d78fe4988f0cc6aa3d093158
