### ISSUE TITLE
Does not respect .eslintignore file

### ISSUE THREAD

**Issue by zfogg** [MoOx/eslint-loader#35]
The one missing feature that makes this unusable for me is that it doesn't respect my project's .eslintignore file :(. Could we fix that? I may do it myself and send a PR if I have time in the next couple weeks :).

**Comment by MoOx** [comment]
I think it's working (at least for me).

**Comment by zfogg** [comment]
It seems to be working now.. strange :3

**Comment by MoOx** [comment]
Good to know !
