### ISSUE TITLE
npm error after update to version 0.11.0

### ISSUE THREAD

**Issue by pahund** [MoOx/eslint-loader#37]
Hi, first of all, thanks for the great work you did on this useful loader!

I have a project that depends on eslint 0.20.0 and eslint-loader 0.11.0 (see my [package.json](https://github.com/pahund/es6box/blob/eslint0.10/package.json)).

When I do _npm install_, I get this error:

npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-loader@0.11.0 wants eslint@>= 0.17 <=0.20

Is it a bug, or am I doing it wrong?

Cheers,
Patrick

**Comment by MoOx** [comment]
Hum. Looks like the range I specified isn't valid  https://github.com/MoOx/eslint-loader/commit/4b50d2e6cc37319bd55b725f2b3f526d21c734f7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R27

Dunno what is wrong https://docs.npmjs.com/misc/semver#hyphen-ranges-x-y-z-a-b-c

Should I use ">=0.17 <0.21" ? Or something else ?

**Comment by MoOx** [comment]
> If a partial version is provided as the second version in the inclusive range, then all versions that start with the supplied parts of the tuple are accepted, but nothing that would be greater than the provided tuple parts.

I think I should use `0.17 - 0.20`.

@pahund Can you try to edit the package.json locally and check if that works ?

**Comment by pahund** [comment]
Yep, that seems to do the trick!

**Comment by MoOx** [comment]
Thanks for helping!
Fix released as 0.11.1
