### ISSUE TITLE
How do you use external .eslintignore file?

### ISSUE THREAD

**Issue by zhon** [MoOx/eslint-loader#46]
I would prefer not to have to duplicate my ignore files inside the webpack module loader.

I tried the following to no avail. 

``` js
  eslint: {
    configFile: '.eslintrc',
    ignoreFile: '.eslintignore',
  },
``
```

**Comment by MoOx** [comment]
Currently it's not handled. But `.eslintignore` should be automatically handled by eslint. Otherwise (custom name) I guess we have to handle this via a new option.

**Comment by MoOx** [comment]
PR welcome :)

**Comment by Semigradsky** [comment]
@zhon you shoul just use `ignorePath` option. Not `ignoreFile`
```js
  eslint: {
    ignorePath: '.eslintignore'
  },
```

**Comment by aethant** [comment]
I'm experiencing the same issue, but `ignorePath` isn't working for me either. It'd be nice if it just auto recognized it. :+1:

**Comment by mbixby** [comment]
As a quick workaround you could probably replace  `executeOnText` with `executeOnFile`, you can get the file path by calling `webpack._module.userRequest` (sans `webpack._module.userRequest`). If you use `executeOnText`, ESLint has no way of knowing the filepath thus applying `.eslintignore`. No additional config is necessary if `.eslintignore` is in webpack's process.cwd.

**Comment by MoOx** [comment]
executeOnText currenctly accept 2 arguments, and the 2nd is the filename.
eslintignore is working thanks to that improvement since 0.12.0

**Comment by mbixby** [comment]
> since 0.12.0

Sounds like a solution to the problem

**Comment by MoOx** [comment]
Han, this issue has been opened AFTER 0.12.0 got released so I unsure if I should keep it open or closed...

**Comment by haf** [comment]
So .eslintignore files don't work -- the lint loader still loads all files. You say I can create some callback function `executeOnText`? Could you document how you make the ignore files apply?

**Comment by mbixby** [comment]
Is your `.eslintignore` in webpack root? (There can be only one.)

**Comment by haf** [comment]
No, it's in the subfolder. According to the docs for eslint you should have able to have it in subfolders; so is this a restriction for the eslint-loader?

**Comment by mbixby** [comment]
http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories
> When ESLint is run, it looks in the current working directory to find an .eslintignore file before determining which files to lint. If this file is found, then those preferences are applied when traversing directories. Only one .eslintignore file can be used at a time, so **.eslintignore files other than the one in the current working directory will not be used.**

**Comment by haf** [comment]
@mbixby You're correct. PEBCAK error.

**Comment by MoOx** [comment]
Closing since I don't see how we could change current behavior.
