### ISSUE TITLE
eslint errors stop build

### ISSUE THREAD

**Issue by josephfinlayson** [MoOx/eslint-loader#48]
I would like my webpack build to continue even though ESLint produces failing errors. This will allow me to quickly prototype code.

My webpack config is as follows:

    eslint: {
        configFile: '.eslintrc',
        emitError: false,
    }

        preLoaders: [{
                test: /\.(js|jsx)$/,
                loader: 'eslint-loader',
                exclude: /(node_modules|bower_components)/
            }]

````
/home/joe/www/frontend/app/modules/account/components/feeds/boxes/facebook-box/facebook-box.jsx
  18:63  error  Multiple spaces found before '}'  no-multi-spaces

✖ 1 problem (1 error, 0 warnings)

100% :
````

webpack remains on 100% but fails to 'emit'

**Comment by nkbt** [comment]
Do you use NoErrorsPlugin in webpack?

Also try to add emitWarnings:false

**Comment by MoOx** [comment]
You should try emitWarnings: true to force warnings.

**Comment by MoOx** [comment]
@josephfinlayson did you still have an issue ?

**Comment by josephfinlayson** [comment]
No, it looked like there were two problems

- NoErrorsPlugin
- eslint-loader was in pre-loaders, if I added it to the main loader, it kept building

Also, generally webpack communicates that it's 'emitted' and shows the list of changed files. With this method the files have changed, but the console doesn't communicate it (it just shows eslint errors)
