### ISSUE TITLE
Broken with ESLint 0.24

### ISSUE THREAD

**Issue by bebraw** [MoOx/eslint-loader#49]
Looks like peer dependency is up to 0.23 and it's not compatible with recently released [0.24](http://eslint.org/blog/2015/06/eslint-0.24.0-released/).

**Comment by mathieumg** [comment]
Wouldn't it be possible to set it to `eslint >= 0.21`?

**Comment by Semigradsky** [comment]
`eslint >= 0.21 < 1` should be fine
http://eslint.org/blog/2015/06/preparing-for-1.0.0/

**Comment by nkbt** [comment]
See #32 

Maybe this time....

**Comment by nkbt** [comment]
@MoOx could you please release a new version with ESLint 0.24 support? Thank you.
