### ISSUE TITLE
Custom location for .eslintrc

### ISSUE THREAD

**Issue by mg** [MoOx/eslint-loader#5]
Hi, is it possible to specify location of eslint configuration file from eslint options in webpack?

**Comment by MoOx** [comment]
Not right now, but this can be added to the loader.

**Comment by MoOx** [comment]
We might want to pass options to the eslint config loader https://github.com/eslint/eslint/blob/cd8637efc989aff7a1cfc4dd19ec70ebdd9253f6/lib/config.js#L236

**Comment by mg** [comment]
Sweet, that worked perfectly
```
eslint: {
  configFile: 'path/.eslintrc'
}
```

Thanks for the help.

**Comment by MoOx** [comment]
I will add that in the readme.
