### ISSUE TITLE
Exit process with code 1 if lint errors

### ISSUE THREAD

**Issue by bsbeeks** [MoOx/eslint-loader#53]
I'm a newbie to webpack and loaders, so forgive me if my terminology is off or this is a question that has already been answered somewhere else.

I would like to use this loader in conjunction with Travis CI to produce passing/failing builds. So, if there are no lint errors, the build passes. Otherwise it should fail. I can get it to fail by adding the following plugin to my webpack config:

```javascript
plugins: [
    function () {
      this.plugin('done', function (stats) {
        if (stats.compilation.errors && stats.compilation.errors.length) {
          console.log(stats.compilation.errors[0].error);
          process.exit(1);
        }
      });
    }
  ]
```

This works great, and the Travis build fails. The problem is that it fails after the first file it finds lint errors in. I'd like it to fail after it lints ALL of the files. So that leads me to 2 questions:

1. Is there a way to have this loader exit with a code of 1 after it lints all the files and displays the error messages?
2. Is there a way within a webpack plugin to capture all the errors from the linter, print them to the terminal, then exit with a code of 1?

**Comment by MoOx** [comment]
webpack should exit 1 if eslint-loader returns some errors (so your eslint config should use 2 in rules conf, not 1 (warning) OR you should use `emitErrors` option of this loader). Also it should by default show all errors/warnings.

So 1. and 2. are kind of the default behavior...

**Comment by bsbeeks** [comment]
That's what I originally thought. But, you can see with the screenshots below, that 1) I am displaying all the errors using 2 in the rules conf 2) Travis is saying the build was successful, even though there were errors in webpack. Note: I've tried using a custom `npm test` task which just runs webpack and I have also tried using just `webpack` directly in Travis.

![screenshot 2015-07-02 07 48 31](https://cloud.githubusercontent.com/assets/714084/8478642/ea57bac6-208f-11e5-91e7-05aaa62e6d13.png)
![screenshot 2015-07-02 07 56 44](https://cloud.githubusercontent.com/assets/714084/8478641/ea563b24-208f-11e5-9f16-bdc33ce170c3.png)

The only way I can get it to exit with a code 1, is to set `failOnError` to `true` in the eslint config or to use the custom plugin mentioned above. But as you can see, it only displays the first file it comes across with errors:

![screenshot 2015-07-02 08 00 55](https://cloud.githubusercontent.com/assets/714084/8478734/7c4d7704-2090-11e5-8060-7142084de759.png)

**Comment by nkbt** [comment]
Use --bail option of webpack. Also consider adding webpack.NoErrorsPlugin

**Comment by bsbeeks** [comment]
The `--bail` option does the same thing as the last screen shot. Shows the error first file with errors, then exits. I'm looking to have it show ALL of the errors, then exit. 

I'll have to look into the NoErrorsPlugin

**Comment by nkbt** [comment]
Oh sorry. I see your issue is different. Not sure why this happens. I
usually get all errors at a time.

What I recommend, not to use loader as part of CI. Use just a normal lint
command. And do build after. Without any extras. This way CI error tracking
and reporting is usually way better.

We use loader for dev only. For prod/pre-commit there is just a normal
eslint CLI.

**Comment by bsbeeks** [comment]
Yeah, I think I'm going to abandon Webpack with Travis CI and just use Grunt or something similar.

**Comment by nkbt** [comment]
You definitely do not need grunt or something. NPM scripts are more then
enough. And keep doing build with webpack, why not? Just have different
configs for prod and dev (one config with options)

**Comment by MoOx** [comment]
@bsbeeks do you rely only on "npm test" on Travis or did you added multiple `scripts`? Because I previously got this issue and I fixed it by using a shell script that does my npm test after another command "set -o errexit" (abort if any command fails).

I would mike to found what is the problem and fix this.

**Comment by MoOx** [comment]
also @bsbeeks do you use eslint as preloader or as a loader ?

**Comment by bsbeeks** [comment]
@MoOx what I'm currently using is the `webpack` command in a Travis script block. I tried eslint as a preloader and loader and didn't see much difference. It's currently set as a preloader. 

I'll try `set -o errexit` and see if that helps.

**Comment by MoOx** [comment]
I would recommand you only rely on one command (npm test) and put a bash script under that alias. It would avoid weird travis behavior on error codes.

**Comment by bsbeeks** [comment]
@MoOx can you post the Travis, Webpack, and package.json settings you're using to get everything to work?

**Comment by MoOx** [comment]
I cannot share my latest project (a bit complicated + private). I will try to make a demo somewhere asap.

**Comment by pstoica** [comment]
So I can get webpack to bail on eslint errors. Unfortunately, I can only get this to show up and not the actual errors:

```
ModuleBuildError: Module build failed: Error: Module failed because of a eslint error.
```

--display-error-details didn't show the rest.

**Comment by pstoica** [comment]
It looks like a fault with the `bail` option: https://github.com/webpack/webpack/issues/711

**Comment by bsbeeks** [comment]
Thanks @pstoica. We've settled with using the small plugin I mentioned about for now. The plugin at least displays the first error.

**Comment by DiscoNova** [comment]
For our project, I've modified the plugin to display all errors instead of just the first one:

```javascript
plugins: [
    function () {
        this.plugin('done', function (stats) {
            if (stats.compilation.errors && stats.compilation.errors.length) {
                console.log('Found following error(s):');
                stats.compilation.errors.forEach(function(theError) {
                    console.log(theError.error);
                });
                process.exit(1);
            }
        });
    }
]
```

**Comment by MoOx** [comment]
1.1.1 with failOnError and failOnWarning now print messages. That might help.
