### ISSUE TITLE
Support for eslint 1.x?

### ISSUE THREAD

**Issue by Dashed** [MoOx/eslint-loader#54]
At the moment eslint v1.x is imminent: https://github.com/eslint/eslint/releases which contain various fixes I'm interested in.

At the moment eslint v0.24 is supported: https://github.com/MoOx/eslint-loader/blob/7a73a4c377cc874245da457e389356b058abcd67/package.json#L28

I'm hoping this loader will work with eslint v1.x without any drastic changes.

**Comment by MoOx** [comment]
Will "^1.0.0" works for rc versions ?

**Comment by Dashed** [comment]
not sure. I'm not familiar with npm version convention beyond the basics.

You can probably adapt using this: https://github.com/yannickcr/eslint-plugin-react/blob/9773cfc72dca92d0f8ece00a096c3795161d571f/package.json#L34

**Comment by Fer0x** [comment]
#55

**Comment by Dashed** [comment]
Thanks @MoOx :+1:
