### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by phaistonian** [MoOx/eslint-loader#61]
Hi.

When using eslint-loader either as preloader or as a loader, I am getting this error:
`Module build failed: Maximum call stack size exceeded`

I am sure it has to do with webpack's resolving stuff, but I have no idea how to resolve it.

If it's any help, this works fine on OSX, not on a Ubuntu system.

Thank you.

**Comment by MoOx** [comment]
No idea. not enough info to help.

**Comment by phaistonian** [comment]
I believe this has to do something with [this](https://github.com/webpack/webpack/issues/175).

**Comment by phaistonian** [comment]
It got fixes along the way.
