### ISSUE TITLE
"Module parse failed"

### ISSUE THREAD

**Issue by mdreizin** [MoOx/eslint-loader#66]
Using of "preLoaders+loaders" causes "Module parse failed":

```javascript
module.exports = {
  module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ],
    loaders: [
      {test: /\.js$/, loader: "babel-loader", exclude: /node_modules/}
    ]
  }
}
```

```
ERROR in ./index.js
Module parse failed: ./node_modules/babel-loader/index.js!./node_modules/eslint-loader/index.js!./index.js Line 3: Unexpected token
You may need an appropriate loader to handle this file type.
```

**Comment by nkbt** [comment]
This is strange, I've got exactly same setup and don't have any issues.

Maybe you need `babel-eslint` in your `.eslintrc`?

**Comment by mdreizin** [comment]
@nkbt I will try to create a repo with example witch causes this error. Let me some time to do it.

**Comment by MoOx** [comment]
It seems you just need babel-eslint as a parser for eslint ;)
Reopen if that is not the case, but each time I got this issue, it's just that I use an esNOTEXISTING feature :)

**Comment by iurii-kondratiuk** [comment]
I have the same issue even if I add `babel-eslint` parser to `.eslintrtc`: 
```
module.exports = {
  module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: [/node_modules/, /lib/]}
    ],
    loaders: [
      {test: /\.js$/, loader: "babel-loader", exclude: [/node_modules/, /lib/]}
    ]
  }
}
```
```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "parser": "babel-eslint"
}
```

**Comment by MoOx** [comment]
What is your input file that trigger an "Unexpected token" issue?
This have probably nothing to do with the fact that you are using eslint as a preloader.
But if you think it is, making a pull request to add a failing test might help us :)

**Comment by iurii-kondratiuk** [comment]
It fails on this line and it works fine if I remove the preloader: 
```
import { accountService } from 'services/account.service.js';
```
And it says: 
```
... Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { accountService } from 'services/account.service.js';
|
...
```

**Comment by MoOx** [comment]
You don't have this issue if used as a loader before (=> after in the array definition) of babel-loader?

**Comment by iurii-kondratiuk** [comment]
I do have it in this case as well.

**Comment by MoOx** [comment]
The issue seems related to eslint. Not this loader.
Do you get the same issue via eslint cli?

**Comment by mdreizin** [comment]
@MoOx I don't get this issue using `eslint` cli directly.

**Comment by iurii-kondratiuk** [comment]
@MoOx I seems that I also don't have it using `eslint` cli directly.

**Comment by gegles** [comment]
I have the exact same issue with all the latest packages installed. Using eslint-loader as a preloader fails!

**Comment by mdreizin** [comment]
@MoOx please reopen it until it will be fixed.

**Comment by gegles** [comment]
Would love to re-open, but I don't have sufficient rights to do so!

Let me know. Thx.

**Comment by MoOx** [comment]
Can someone open a PR with a failing test?
I don't have the issue at the moment, maybe it's related to a recent eslint change?

**Comment by schickling** [comment]
Having the same problem

**Comment by MoOx** [comment]
This module is open source and covered by tests. It is very easy to start working on it: clone the project, the `npm install && npm test`.

So if you encounter a bug, please take the time to fix it (reminder: Open Source projects work even better with multiples contributors).

If don't want to take the time to fix it because you have others priorities, at least make a pull request with a failing test to expose the bug to the world in order to facilitate things for people that will fix it.
 
Thanks !

**Comment by Halama** [comment]
Hi I have the same issue. I wasn't able to run the tests without errors yet. So I've create the repository which demonstrates the bug https://github.com/Halama/eslint-loader-debug

**Comment by MoOx** [comment]
Thanks a lot, that will helps. It's look like it's related to your version of babel.

Can everyone involved here tell which version of babel you are using? babel@6?

(I still use babel@5, that probably why I don't have the issue yet)

**Comment by MoOx** [comment]
This might be related https://github.com/babel/babel-eslint/issues/199 / https://github.com/babel/babel-eslint/pull/202 but I am not sure

**Comment by iurii-kondratiuk** [comment]
@MoOx I'm using `"babel": "^6.0.15"`

**Comment by schickling** [comment]
```
    "babel-core": "^6.1.2",
    "babel-eslint": "^4.1.4",
    "babel-loader": "^6.0.1",
    "babel-preset-es2015": "^6.1.2",
    "babel-preset-react": "^6.1.2",
    "babel-runtime": "^6.0.14",
```

**Comment by MoOx** [comment]
So like I said, it looks like it is related to the  babel-eslint issue mentioned above (not upgraded to babel 6 yet).

**Comment by mdreizin** [comment]
I don't use `babel@6` and here is my config:

```json
{
    "babel": "^5.8.29",
    "babel-core": "^5.8.30",
    "babel-loader": "^5.3.2",
    "eslint": "^1.7.3",
    "eslint-loader": "^1.1.0",
    "webpack": "^1.12.1"
}
```

**Comment by mdreizin** [comment]
@MoOx Could you please tell us about the progress?

**Comment by MoOx** [comment]
I didn't do anything yet because I don't have the issue with all my current project atm.

Also see https://github.com/MoOx/eslint-loader/issues/66#issuecomment-154508816 if you want to help.

**Comment by gegles** [comment]
Everything is now working great for me after upgrading to the latest babel, etc.. 

Thanks. G.

**Comment by Laiff** [comment]
Problem was in babel-loader, for babel@5 you may use babel-loader@5.4.0 it works fine with preLoaders

**Comment by MoOx** [comment]
Thanks for reporting this babel issue.

**Comment by stilllife00** [comment]
same problem here after migrating to Webpack 2.0 even with babel-loader 6 and 7

    ERROR in ./src/index.jsx
    Module parse failed: /var/www/images-shelf/node_modules/eslint-loader/index.js!/var/www/images-    shelf/src/index.jsx Unexpected token (18:12)
    You may need an appropriate loader to handle this file type.
    | render() {
    |         return (
    |             <h1>
    |                 Test
    |             </h1>

"babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.2.2",
    "babel-jest": "^18.0.0",
    "babel-loader": "^6.4.1",

"eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-loader": "^1.7.1",


    rules: [
            {
                enforce: "pre",
                test: /\.jsx?$/,
                loaders: "eslint-loader",
                include: [
                    config.paths.src
                ]
            },

**Comment by NicolasRannou** [comment]
@stilllife00 did you find out how to fix it?

**Comment by NicolasRannou** [comment]
OK my issue was that I was using rules + loaders at the same time. Only using rules fixes it!
