### ISSUE TITLE
Any way to still allow the build to complete?

### ISSUE THREAD

**Issue by waeljammal** [MoOx/eslint-loader#68]
Hi,

I am using my loader like this:
loaders: ['babel', 'eslint-loader']

However when the lint has errors it stops babel from running, I'd like to prevent this during dev mode using hot reload and allow the errors though, the devs can use console.log etc during dev but in production I would want the build to actually fail.

Thanks

**Comment by nkbt** [comment]
put eslint-loader to pre-loaders and do not stop on errors (webpack plugin, if you have it).

**Comment by MoOx** [comment]
@waeljammal you should take a look at the options https://github.com/MoOx/eslint-loader#emitwarning-default-false
