### ISSUE TITLE
webpack doesn't recompile changes if you make a style change

### ISSUE THREAD

**Issue by jonathanong** [MoOx/eslint-loader#69]
i'm not sure if this is an issue with the loader or my whole setup. when watching, if you do a code change that is only a style change, it does not recompile.

http://cl.ly/3K2j3C0j0D15

using `eslint-loader@1.1.1`

loader setup is: 

```
[
      // babel + jsx loader
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [
          'babel'
        ]
      },
      // eslint loader - needs to be below babel
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'eslint-loader'
      },
      // json loader
      {
        test: /\.json$/,
        loaders: [
          'json'
        ]
      },
      // sass loader
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!sass-loader')
      },
      // css loader
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
      },
      // added specifically for svg images in css, this will inline them as base64 strings
      {
        test: /\.(svg)$/,
        loader: 'url-loader?limit=100000'
      }
    ],
```

has anyone else experienced this problem?

**Comment by MoOx** [comment]
Nope. That's might be related to webpack caching system...
Why do you defined 2 sections for eslint and babel?

**Comment by jonathanong** [comment]
yeah i'm thinking the same. webpack might be caching too inteligently

i copied your readme https://github.com/MoOx/eslint-loader#usage lol does having two sections matter?

**Comment by MoOx** [comment]
Might affect webpack caching (no idea lol). Can you try with one section?

```js
{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [
          'babel-loader',
          'eslint-loader',
        ]
      },
```

**Comment by moklick** [comment]
Maybe because of the ExtractTextPlugin?

**Comment by MoOx** [comment]
@jonathanong did you still have the issue?

**Comment by jonathanong** [comment]
i don't know because i just removed this library

**Comment by MoOx** [comment]
hum ok...

**Comment by rattrayalex** [comment]
FWIW, my guess is Babel is caching based on AST, which doesn't change when you make a stylistic change.
