### ISSUE TITLE
Custom .eslintrc not respected

### ISSUE THREAD

**Issue by marvinhagemeister** [MoOx/eslint-loader#73]
We have two different eslint configuration files. One is intended for production and final builds and the other one is for development purposes and thus less strict (allows console.log for example). The `configFile` option doesn't seem to work for me.

folder structure:
```
/
  .dev.eslintrc
  webpack.config.js
```
My webpack config

```js
...
module: {
  preLoaders: [
    {test: /\.js$/, loader: 'eslint-loader', exclued: /node_modules/}
  ],
  loaders: [
    {test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/}
  ],
  eslint: {
    configFile: path.join(__dirname, '.dev.eslintrc')
  }
}
```

**Comment by MoOx** [comment]
The eslint section should not be in module section.

**Comment by marvinhagemeister** [comment]
Awesome thanks!
