### ISSUE TITLE
Stop webpack from outputting file list

### ISSUE THREAD

**Issue by josebalius** [MoOx/eslint-loader#74]
Maybe this is not possible but at the moment whenever eslint throws a warning or error, webpack proceeds to output the whole file list and then shows the errors at the bottom.

Is there anyway to only see eslint's info without webpack's file list dump?

Thanks!

**Comment by MoOx** [comment]
This is probably a webpack configuration issue, more than an eslint-loader one.

If you are using webpack-dev-server you can use the following config:

```
module.exports =  {
  // webpack-dev-server config
  devServer: {
    // webpack output options
    stats: {
      // hide all chunk dependencies because it's unreadable
      chunkModules: false,
      // noize
      assets: false,
    },
  },
```

**Comment by josebalius** [comment]
@MoOx Thank you! exactly what it was.
