### ISSUE TITLE
Bump peerDependencies to support ESLint 2.0.0

### ISSUE THREAD

**Issue by bebraw** [MoOx/eslint-loader#79]
[2.0.0](http://eslint.org/blog/2016/02/eslint-v2.0.0-released) was just released. Good time to bump. :+1:

**Comment by zfogg** [comment]
+1

**Comment by patrickheeney** [comment]
Just got blocked by this as well.

**Comment by idolize** [comment]
Likewise hitting this issue (build server is using npm v2, so it won't even install)
