### ISSUE TITLE
ESlint errors clutter browser console

### ISSUE THREAD

**Issue by josephfinlayson** [MoOx/eslint-loader#84]
Is there any way to stop these errors being transmitted to the console?

**Comment by MoOx** [comment]
Webpack handle the output. This loader only emits eslint results. Why do you want to use this loader if that's not to see the errors?

**Comment by josephfinlayson** [comment]
I'm happy with stderr and also I have a growl plugin. I just don't want them to be in my chrome console :)

**Comment by MoOx** [comment]
Oh you mean browser console. Ok then it's definitely something to handle in webpack configuration (and I have no idea how).

**Comment by josephfinlayson** [comment]
Thanks for the quick response. I hope someone sees this and can help!

**Comment by MoOx** [comment]
Maybe you can ask in webpack repo or gitter chan.

**Comment by nkbt** [comment]
I reckon it is a good thing that makes you fix your lint errors ;)

**Comment by sdtsui** [comment]
@josephfinlayson please reference the issue in webpack if you get help for this. I'm also interested. 

I have this package as part of our build process. Overall, it's great. Would love it if our browserSync + webpack hot reload setup did not render the errors from `eslint-loader`, and simply output them to terminal.

**Comment by MoOx** [comment]
Not an eslint-loader issue, closing.

**Comment by stevenmusumeche** [comment]
I have the opposite problem.  My eslint errors are not displaying in the browser console but I want them to.

**Comment by JikkuJose** [comment]
Anyone has a solution for this. I seriously don't understand how someone thinks its a good idea to pollute the already small browser console with liniting warnings! Disabling the loader completely is to stop those warnings defeats the whole purpose.

**Comment by MoOx** [comment]
@JikkuJose it's a webpack configuration from what I know. Please check webpack issue tracker.

**Comment by aamirshah** [comment]
Did any one find a solution for it?
