### ISSUE TITLE
Parsing error JSX

### ISSUE THREAD

**Issue by votinhaooo** [MoOx/eslint-loader#85]
I'm trying to use 2 loaders: babel and eslint
It's ok when i only use babel
Webpack.config.js

```
...
module: {
    loaders: [
      {
        test: /\.js?$/,
        exclude: /(node_modules|bower_components)/,
        loader: "babel-loader?presets[]=react,presets[]=es2015"
      }
    ]
  },
...
```
But when i use 2 loaders
```
...
module: {
    loaders: [
      {
        test: /\.js?$/,
        exclude: /(node_modules|bower_components)/,
        loaders: ["babel-loader?presets[]=react,presets[]=es2015", "eslint-loader"]
      }
    ]
  },
...
```
i got an error in index.js file
`5:17  error  Parsing error: Unexpected token <`

index.js
```
var ReactDOM = require('react-dom')
var App = require('./App')

ReactDOM.render(<App />, document.getElementById('root'))
```

**Comment by MoOx** [comment]
You probably didn't configured eslint correctly http://eslint.org/docs/user-guide/configuring#specifying-parser-options.

Note that loaders are executed from right to left, so eslint is executed first and need to know about the jsx thing.
