### ISSUE TITLE
Problems with ESLint 2.10.1 and babel-eslint

### ISSUE THREAD

**Issue by bebraw** [MoOx/eslint-loader#92]
There's something going on with ESLint 2.10.1, eslint-loader, and babel-eslint combination. They had [an issue in 2.10.0](https://github.com/eslint/eslint/issues/6158) that broken eslint-loader and babel-eslint. It was fixed in 2.10.1. It still fails with eslint-loader, though.

I set up [an example illustrating this](https://github.com/survivejs/react-boilerplate/tree/eslint-2.10.1). If you execute `npm run test:lint`, the linting process completes successfully. If you run `npm start`, you'll start seeing errors like this:

```bash
ERROR in ./app/index.jsx

.../react-boilerplate/app/index.jsx
  1:1  error  Parsing error: The keyword 'import' is reserved

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/Notes.jsx

.../react-boilerplate/app/Notes.jsx
  1:1  error  Parsing error: The keyword 'import' is reserved

✖ 1 problem (1 error, 0 warnings)
```

It's not picking up the parser for some reason. I did try setting

```javascript
  eslint: {
    configFile: path.join(__dirname, '.eslintrc')
  }
```

at my `common` configuration to make sure it really points to the configuration but this didn't have any effect.

It's possible this is ESLint core issue and that their fix missed some corner case breaking ESLint. I am opening the issue here to see if other users are seeing similar behavior with this particular combination.

**Comment by MoOx** [comment]
Waiting for https://github.com/eslint/eslint/issues/6182 to be fixed.

**Comment by swarthy** [comment]
As temporary solution you can set parser in query in webpack.config.js
```javascript
preLoaders: [
      {
        test: /\.js$/,
        loader: 'eslint?parser=babel-eslint',
        exclude: /node_modules/,
      }
    ],
```

**Comment by sebinsua** [comment]
I'm getting an error which looks like:

```
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
```

Not sure if it's the same problem.

**Comment by bebraw** [comment]
@sebinsua You could try against https://github.com/eslint/eslint/pull/6183 . There's a proposed fix.

**Comment by bebraw** [comment]
Closing given the combination works again. 👍
