### ISSUE TITLE
webpack-dev-server and white spaces eslint errors 

### ISSUE THREAD

**Issue by dizzyn** [MoOx/eslint-loader#95]
Can I force the reload even if "Nothing changed" from code functionality point of view. When I modify whitespace for eslint rules like "no-trailing-spaces" etc. The dev-server will skip the reload process.

I use:
- webpack-dev-server (1.14.1)
- eslint-loader (1.3.0)
- eslint (2.9.0)

My configuration looks this way:

```
loaders: [
            {
                test: /\.js?$/,
                exclude: /(node_modules)/,
                loader: ['babel-loader', 'eslint-loader']
            },
```

Thank you.

**Comment by MoOx** [comment]
Dup of #78
