### ISSUE TITLE
ESLint 3.0 is out

### ISSUE THREAD

**Issue by avindra** [MoOx/eslint-loader#96]
This warning is emitted upon  installation with `eslint@3.0.0`:

> npm WARN eslint-loader@1.3.0 requires a peer of eslint@>=1.6.0 <3.0.0 but none was installed.

**Comment by MoOx** [comment]
Are you aware of any breaking changes that might affect this loader?

**Comment by avindra** [comment]
I read the release notes and saw the only breaking changes were to the
default rules, so it shouldn't impact the loader.

**Comment by avindra** [comment]
The only change I see which may have some impact:

e0d4b19 Breaking: Error thrown/printed if no config found (fixes #5987)
(#6538) (Kevin Partington)

**Comment by klimashkin** [comment]
I checked, it works fine for me with eslint 3
So you can update peer

**Comment by avindra** [comment]
I've also tested our project with Eslint 3.0 and found no issues.

**Comment by klimashkin** [comment]
And the sooner the better, without this nobody can create shrinkwrap in theirs project :)
`ERR! peer invalid: eslint@>=1.6.0 <3.0.0, required by eslint-loader@1.3.0`

**Comment by MoOx** [comment]
Support added in 1.4.0
