### ISSUE TITLE
.eslintignore is ..ignored?

### ISSUE THREAD

**Issue by phaistonian** [MoOx/eslint-loader#97]
Hello.

Since the new release, it seems that the `.eslintignore` file located in the project's root is ignored.

Thing is, it's respected when running eslint inside the project.

ps: It could just be a breaking change in 3.0.0 that has to be treated in the loader.

**Comment by MoOx** [comment]
As you can see https://github.com/MoOx/eslint-loader/commit/427f143f518f45935e9f6cb759c898ffa5e03fea the support for 3.x is pretty simple.
Nothing is mentionned about this in eslint CHANGELOG http://eslint.org/blog/2016/07/eslint-v3.0.0-released#breaking-changes
Not sure what is wrong... Maybe this commit changed something https://github.com/eslint/eslint/commit/e0d4b19 ?

**Comment by phaistonian** [comment]
Yes, I noticed that nothing much has changed as far as the loader is concerned. 

I managed to get this up and running in my local system by explicitly setting the `.eslintignore` path in the config, however, for the life of me, I can't get it to work on the Linux system where the exact same repo also lives.

I will try and figure this out and get back to you in case something meaningful comes up.

**Comment by joshkel** [comment]
I ran into this today as well. As far as I can tell, this is the result of eslint/eslint#6305. Adding a third parameter, `true`, to the `executeOnText` call fixes it.

**Comment by phaistonian** [comment]
Great find @joshkel.

Waiting for the new release, then.

**Comment by MoOx** [comment]
Closed by b976c83ea958030fe4c4fa80f8583e10302e3447
