### ISSUE TITLE
Adding custom rules

### ISSUE THREAD

**Issue by casertap** [MoOx/eslint-loader#98]
I created a folder: `eslint-rules`
I added my custom rule file: `t-for-type-only.js`

```
"use strict";

module.exports = function(context) {
  return {
    MemberExpression: function(node) {
      var objectName = node.object.name,
          propertyName = node.property.name;
      if (objectName === "t" && !node.computed && propertyName.match(/^[a-z].*$/)) {
        context.report(node, "t is used in another context than Type t.{{property}}.", { property: propertyName });
      }
    }
  };
}
```

My webpack config `dev.config.js`

```
  module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /node_modules/, loaders: ['babel?' + JSON.stringify(babelLoaderQuery), 'eslint-loader']},
 ...
,
  eslint: {
    rulesdir: 'eslint-rules/'
  },
```

but it does not work. How do I add a folder with custom rules with eslint-loader?

**Comment by MoOx** [comment]
No idea.

**Comment by casertap** [comment]
It could be good to add support for that.
Here is the doc about the rulesdir option. 
It is a command line option I am not sure how to handle this.
http://eslint.org/docs/user-guide/command-line-interface#options

**Comment by casertap** [comment]
Any plan to do something about it?

**Comment by MoOx** [comment]
PR are always welcome.

**Comment by taylor1791** [comment]
I was able to get this to work by adding `rulesDir: 'dir'` to my webpack config. Make sure you enable the rule in the config file as well.

**Comment by MoOx** [comment]
Closing to due to lack of feedback.
